apiVersion: v1
kind: Service
metadata:
  name: jenkins-nginx-service
  namespace: devops
spec:
  selector:
    app: jenkins-nginx
  ports:
    - name: jenkins-nginx
      protocol: TCP
      port: 9999
      targetPort: 9999
