apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops
spec:
  selector:
    app: jenkins
  ports:
    - name: jenkins-http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: jenkins-https
      protocol: TCP
      port: 443
      targetPort: 8443
    - name: jenkins-slave
      port: 50000
      protocol: TCP
      targetPort: 50000
