apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: jenkins-volume-claim
  namespace: devops
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: jenkins-volume
