apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
